"""Initial migration.

Revision ID: 3b0abfeb3613
Revises: 28e2eee93967
Create Date: 2021-08-15 14:58:28.417579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b0abfeb3613'
down_revision = '28e2eee93967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('slug', sa.String(length=100), nullable=True))
    op.add_column('post', sa.Column('tags', sa.String(length=100), nullable=True))
    op.add_column('post', sa.Column('category', sa.String(length=100), nullable=True))
    op.alter_column('post', 'meta_description',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'meta_description',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('post', 'category')
    op.drop_column('post', 'tags')
    op.drop_column('post', 'slug')
    # ### end Alembic commands ###
